FROM python:3.8

WORKDIR /code

RUN pip3 install --no-cache-dir pip==22.1.1

COPY requirements.txt requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

EXPOSE 5002

ENTRYPOINT ["gunicorn","-w","2","--threads","2","-b","0.0.0.0:5002","tsp-fc:app"]
